"use client";
import { useMemo, useState, type FormEvent } from "react";
import { DomainPageShell } from "../../components/domain-shell";
import { useStewardshipPortfolio } from "../../lib/stewardship-client";
import type { CanonicalKind } from "../../lib/stewardship-model";

const labels: Record<CanonicalKind, string> = { product: "Product", organization: "Organization", configuration_node: "Configuration node" };
export default function StewardshipPage() {
  const { portfolio, loading, error, mutate } = useStewardshipPortfolio();
  const [kind, setKind] = useState<CanonicalKind>("product");
  const [alias, setAlias] = useState({ entityId: "", alias: "", namespace: "name", sourceReference: "" });
  const [merge, setMerge] = useState({ sourceEntityId: "", targetEntityId: "", rationale: "", sourceReference: "" });
  const [notice, setNotice] = useState("");
  const [saving, setSaving] = useState(false);
  const entities = useMemo(() => portfolio.entities.filter((item) => item.kind === kind), [portfolio.entities, kind]);
  async function act(body: Record<string, unknown>, message: string) { setSaving(true); setNotice(""); try { await mutate(body); setNotice(message); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Update failed."); } finally { setSaving(false); } }
  async function saveAlias(event: FormEvent) { event.preventDefault(); await act({ action: "save_alias", entityKind: kind, ...alias }, "Alias accepted."); setAlias({ entityId: "", alias: "", namespace: "name", sourceReference: "" }); }
  async function mergeEntity(event: FormEvent) { event.preventDefault(); await act({ action: "merge_entity", entityKind: kind, ...merge }, "Canonical references reconciled."); setMerge({ sourceEntityId: "", targetEntityId: "", rationale: "", sourceReference: "" }); }
  return <DomainPageShell title="Identity Stewardship" subtitle="Govern canonical Products, Organizations, and configuration-node aliases." releaseScope={`${portfolio.aliases.filter((item) => item.status === "accepted").length} accepted aliases`} contextMode="portfolio">
    <section className="decision-principle"><strong>Stewardship rule</strong><span>Source text is retained. An alias changes canonical resolution; a merger also reconciles current references and is recorded in the audit log. Configuration-node mergers remain blocked because placement conflicts require individual review.</span></section>
    <section className="summary"><div className="metric"><span>Canonical entities</span><strong>{portfolio.entities.length}</strong><small>Products, organizations, and nodes</small></div><div className="metric"><span>Accepted aliases</span><strong>{portfolio.aliases.filter((item) => item.status === "accepted").length}</strong><small>Governed name mappings</small></div><div className="metric"><span>Merge events</span><strong>{portfolio.merges.length}</strong><small>Retained reconciliation history</small></div></section>
    <section className="domain-section"><div className="section-toolbar"><div><span className="eyebrow">CANONICAL REGISTER</span><h3>Identity inventory</h3></div><select value={kind} onChange={(event) => { setKind(event.target.value as CanonicalKind); setAlias({ ...alias, entityId: "" }); setMerge({ ...merge, sourceEntityId: "", targetEntityId: "" }); }}>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}s</option>)}</select></div>{loading ? <p>Loading identity register…</p> : error ? <p className="error-copy">{error}</p> : <div className="domain-table-wrap"><table><thead><tr><th>Canonical name</th><th>Type / short name</th><th>Active references</th><th>Accepted aliases</th></tr></thead><tbody>{entities.map((entity) => <tr key={entity.id}><td><strong>{entity.name}</strong><small className="mono">{entity.id}</small></td><td>{entity.secondary || "—"}</td><td>{entity.referenceCount}</td><td>{portfolio.aliases.filter((item) => item.entityKind === kind && item.entityId === entity.id && item.status === "accepted").map((item) => item.alias).join(" · ") || "None"}</td></tr>)}</tbody></table></div>}</section>
    <section className="split-layout"><form className="domain-section governed-editor" onSubmit={(event) => void saveAlias(event)}><span className="eyebrow">ACCEPT ALIAS</span><h3>Map a reported name to a canonical record</h3><label className="modal-field">Canonical {labels[kind]}<select required value={alias.entityId} onChange={(event) => setAlias({ ...alias, entityId: event.target.value })}><option value="">Choose record</option>{entities.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="modal-field">Reported alias<input required value={alias.alias} onChange={(event) => setAlias({ ...alias, alias: event.target.value })} /></label><div className="form-grid"><label className="modal-field">Namespace<select value={alias.namespace} onChange={(event) => setAlias({ ...alias, namespace: event.target.value })}><option value="name">Name</option><option value="supplier_code">Supplier code</option><option value="external_id">External ID</option></select></label><label className="modal-field">Source reference<input value={alias.sourceReference} onChange={(event) => setAlias({ ...alias, sourceReference: event.target.value })} placeholder="Workbook, CM record, or decision" /></label></div><button className="primary-button" disabled={saving}>Accept alias</button></form>
      <form className="domain-section governed-editor" onSubmit={(event) => void mergeEntity(event)}><span className="eyebrow">RECONCILE DUPLICATE</span><h3>Merge a duplicate into the retained record</h3><p className="entity-meta">Available for Products and Organizations. The source record remains in the merger history and becomes an accepted alias.</p><label className="modal-field">Duplicate source<select required value={merge.sourceEntityId} onChange={(event) => setMerge({ ...merge, sourceEntityId: event.target.value })}><option value="">Choose duplicate</option>{entities.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="modal-field">Retained target<select required value={merge.targetEntityId} onChange={(event) => setMerge({ ...merge, targetEntityId: event.target.value })}><option value="">Choose retained record</option>{entities.filter((item) => item.id !== merge.sourceEntityId).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="modal-field">Rationale<textarea required rows={3} value={merge.rationale} onChange={(event) => setMerge({ ...merge, rationale: event.target.value })} /></label><label className="modal-field">Source reference<input value={merge.sourceReference} onChange={(event) => setMerge({ ...merge, sourceReference: event.target.value })} /></label><button className="primary-button" disabled={saving || kind === "configuration_node"}>Reconcile identities</button></form></section>
    <section className="domain-section"><div className="section-toolbar"><div><span className="eyebrow">MERGE HISTORY</span><h3>Canonical reconciliation audit</h3></div></div><div className="domain-list">{portfolio.merges.map((item) => <article className="domain-card" key={item.id}><span className="record-type">{labels[item.entityKind]}</span><h3>{item.sourceName} → {item.targetName}</h3><p>{item.rationale}</p><small>{new Date(item.mergedAt).toLocaleString()} · {item.sourceReference || "No external reference"}</small></article>)}{!portfolio.merges.length ? <p className="empty">No canonical mergers recorded.</p> : null}</div></section>
    {notice ? <p className="toast">{notice}</p> : null}
  </DomainPageShell>;
}
