PRAGMA foreign_keys=ON;

CREATE TABLE `program` (`id` text PRIMARY KEY NOT NULL, `name` text NOT NULL, `description` text, `timezone` text DEFAULT 'UTC' NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `program_name_uq` ON `program` (`name`);
CREATE TABLE `source_package` (`id` text PRIMARY KEY NOT NULL, `program_id` text NOT NULL REFERENCES `program`(`id`), `source_system` text, `file_name` text NOT NULL, `sheet_name` text, `content_hash` text NOT NULL, `source_as_of` text, `received_at` text NOT NULL, `status` text DEFAULT 'received' NOT NULL, `row_count` integer DEFAULT 0 NOT NULL, `accepted_count` integer DEFAULT 0 NOT NULL, `exception_count` integer DEFAULT 0 NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `source_package_hash_uq` ON `source_package` (`program_id`,`content_hash`);
CREATE INDEX `source_package_status_ix` ON `source_package` (`program_id`,`status`,`received_at`);
CREATE TABLE `release` (`id` text PRIMARY KEY NOT NULL, `program_id` text NOT NULL REFERENCES `program`(`id`), `code` text, `normalized_code` text, `name` text NOT NULL, `normalized_name` text NOT NULL, `status` text DEFAULT 'planned' NOT NULL, `target_date` text, `actual_date` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `release_code_uq` ON `release` (`program_id`,`normalized_code`);
CREATE UNIQUE INDEX `release_name_uq` ON `release` (`program_id`,`normalized_name`);
CREATE INDEX `release_status_ix` ON `release` (`program_id`,`status`);
CREATE TABLE `configuration_baseline` (`id` text PRIMARY KEY NOT NULL, `program_id` text NOT NULL REFERENCES `program`(`id`), `release_id` text NOT NULL REFERENCES `release`(`id`), `name` text NOT NULL, `normalized_name` text NOT NULL, `maturity` text DEFAULT 'reported' NOT NULL, `as_of` text NOT NULL, `status` text DEFAULT 'working' NOT NULL, `description` text, `parent_baseline_id` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `baseline_release_name_asof_uq` ON `configuration_baseline` (`release_id`,`normalized_name`,`as_of`);
CREATE INDEX `baseline_release_ix` ON `configuration_baseline` (`program_id`,`release_id`,`status`);
CREATE TABLE `organization` (`id` text PRIMARY KEY NOT NULL, `program_id` text NOT NULL REFERENCES `program`(`id`), `name` text NOT NULL, `normalized_name` text NOT NULL, `organization_type` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `organization_name_uq` ON `organization` (`program_id`,`normalized_name`);
CREATE TABLE `configuration_node` (`id` text PRIMARY KEY NOT NULL, `program_id` text NOT NULL REFERENCES `program`(`id`), `parent_id` text, `node_type` text NOT NULL, `code` text, `normalized_code` text, `name` text NOT NULL, `normalized_name` text NOT NULL, `description` text, `owner_organization_id` text REFERENCES `organization`(`id`), `created_at` text NOT NULL, `updated_at` text NOT NULL, CONSTRAINT `configuration_node_not_self` CHECK (`parent_id` IS NULL OR `parent_id` <> `id`));
CREATE UNIQUE INDEX `configuration_node_code_uq` ON `configuration_node` (`program_id`,`normalized_code`);
CREATE UNIQUE INDEX `configuration_node_position_uq` ON `configuration_node` (`program_id`,`parent_id`,`node_type`,`normalized_name`);
CREATE INDEX `configuration_node_parent_ix` ON `configuration_node` (`program_id`,`parent_id`,`node_type`);
CREATE TABLE `product` (`id` text PRIMARY KEY NOT NULL, `program_id` text NOT NULL REFERENCES `program`(`id`), `canonical_name` text NOT NULL, `normalized_name` text NOT NULL, `short_name` text, `product_type` text, `software_classification` text, `owner_organization_id` text REFERENCES `organization`(`id`), `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `product_name_uq` ON `product` (`program_id`,`normalized_name`);
CREATE INDEX `product_search_ix` ON `product` (`program_id`,`short_name`);
CREATE TABLE `product_supplier` (`product_id` text NOT NULL REFERENCES `product`(`id`), `organization_id` text NOT NULL REFERENCES `organization`(`id`), `supplier_role` text NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `product_supplier_uq` ON `product_supplier` (`product_id`,`organization_id`,`supplier_role`);
CREATE TABLE `capability` (`id` text PRIMARY KEY NOT NULL, `program_id` text NOT NULL REFERENCES `program`(`id`), `parent_id` text, `code` text, `name` text NOT NULL, `normalized_name` text NOT NULL, `description` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `capability_name_uq` ON `capability` (`program_id`,`normalized_name`);
CREATE INDEX `capability_parent_ix` ON `capability` (`program_id`,`parent_id`);
CREATE TABLE `product_capability` (`product_id` text NOT NULL REFERENCES `product`(`id`), `capability_id` text NOT NULL REFERENCES `capability`(`id`), `relationship` text DEFAULT 'satisfies' NOT NULL, `rationale` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `product_capability_uq` ON `product_capability` (`product_id`,`capability_id`,`relationship`);
CREATE TABLE `deployment` (`id` text PRIMARY KEY NOT NULL, `program_id` text NOT NULL REFERENCES `program`(`id`), `product_id` text NOT NULL REFERENCES `product`(`id`), `configuration_node_id` text NOT NULL REFERENCES `configuration_node`(`id`), `environment` text DEFAULT 'unknown' NOT NULL, `site` text DEFAULT 'unknown' NOT NULL, `deployment_role` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `deployment_position_uq` ON `deployment` (`program_id`,`product_id`,`configuration_node_id`,`environment`,`site`);
CREATE INDEX `deployment_node_ix` ON `deployment` (`configuration_node_id`,`product_id`);
CREATE TABLE `baseline_node_state` (`id` text PRIMARY KEY NOT NULL, `program_id` text NOT NULL REFERENCES `program`(`id`), `baseline_id` text NOT NULL REFERENCES `configuration_baseline`(`id`), `configuration_node_id` text NOT NULL REFERENCES `configuration_node`(`id`), `source_row_id` text, `storage_type` text, `storage_gb` real, `cpu_cores` real, `ram_gb` real, `state_notes` text, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `baseline_node_state_uq` ON `baseline_node_state` (`baseline_id`,`configuration_node_id`);
CREATE INDEX `baseline_node_state_node_ix` ON `baseline_node_state` (`baseline_id`,`configuration_node_id`);
CREATE TABLE `baseline_deployment_state` (`id` text PRIMARY KEY NOT NULL, `program_id` text NOT NULL REFERENCES `program`(`id`), `baseline_id` text NOT NULL REFERENCES `configuration_baseline`(`id`), `deployment_id` text NOT NULL REFERENCES `deployment`(`id`), `source_row_id` text, `reported_version` text, `presence` text DEFAULT 'unknown' NOT NULL, `status` text DEFAULT 'reported' NOT NULL, `installation_type` text, `containerized` text, `container_technology` text, `container_type` text, `language` text, `notes` text, `created_at` text NOT NULL, `updated_at` text NOT NULL, CONSTRAINT `baseline_deployment_presence` CHECK (`presence` IN ('present','absent','unknown')));
CREATE UNIQUE INDEX `baseline_deployment_state_uq` ON `baseline_deployment_state` (`baseline_id`,`deployment_id`);
CREATE INDEX `baseline_deployment_state_baseline_ix` ON `baseline_deployment_state` (`baseline_id`,`status`,`presence`);
CREATE TABLE `source_row_24` (`id` text PRIMARY KEY NOT NULL, `source_package_id` text NOT NULL REFERENCES `source_package`(`id`), `source_key` text, `row_number` integer NOT NULL, `row_hash` text NOT NULL, `raw_payload` text NOT NULL, `release_name` text, `tier` text, `resource` text, `tech_stack_type` text, `short_name` text, `hw_host` text, `hw_storage_type` text, `hw_storage_gb` text, `hw_cpu_cores` text, `hw_ram_gb` text, `sw_language` text, `software_type` text, `oem` text, `containerized` text, `container_technology` text, `container_type` text, `long_name` text, `notes` text, `capability_notes` text, `notes_1` text, `notes_2` text, `notes_3` text, `notes_4` text, `release_id` text REFERENCES `release`(`id`), `baseline_id` text REFERENCES `configuration_baseline`(`id`), `configuration_node_id` text REFERENCES `configuration_node`(`id`), `product_id` text REFERENCES `product`(`id`), `deployment_id` text REFERENCES `deployment`(`id`), `materialization_status` text DEFAULT 'unreviewed' NOT NULL, `created_at` text NOT NULL, `updated_at` text NOT NULL);
CREATE UNIQUE INDEX `source_row_package_key_uq` ON `source_row_24` (`source_package_id`,`source_key`);
CREATE UNIQUE INDEX `source_row_package_number_uq` ON `source_row_24` (`source_package_id`,`row_number`);
CREATE INDEX `source_row_review_ix` ON `source_row_24` (`source_package_id`,`materialization_status`,`row_number`);
CREATE INDEX `source_row_release_ix` ON `source_row_24` (`release_id`,`baseline_id`);
CREATE TABLE `audit_event` (`id` text PRIMARY KEY NOT NULL, `program_id` text NOT NULL REFERENCES `program`(`id`), `actor_id` text, `action` text NOT NULL, `entity_kind` text NOT NULL, `entity_id` text NOT NULL, `before_payload` text, `after_payload` text, `created_at` text NOT NULL);
CREATE INDEX `audit_entity_ix` ON `audit_event` (`program_id`,`entity_kind`,`entity_id`,`created_at`);
CREATE INDEX `audit_actor_ix` ON `audit_event` (`program_id`,`actor_id`,`created_at`);
