"use client";

import { useState } from "react";
import * as XLSX from "xlsx";
import Link from "../../../components/app-link";
import { DomainPageShell } from "../../../components/domain-shell";
import { CHANGE_REQUEST_IMPORT_COLUMNS, normalizeChangeRequestImportRow, type ChangeRequestImportPreview, type ChangeRequestImportRow } from "../../../lib/change-import";

export default function ChangeRequestImportPage() {
  const [fileName, setFileName] = useState(""); const [sheetName, setSheetName] = useState(""); const [rows, setRows] = useState<ChangeRequestImportRow[]>([]); const [preview, setPreview] = useState<ChangeRequestImportPreview | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function chooseFile(file?: File) { if (!file) return; setMessage(""); setPreview(null); setFileName(file.name); try { const workbook = XLSX.read(await file.arrayBuffer(), { type: "array" }); const first = workbook.SheetNames[0]; if (!first) throw new Error("The workbook has no worksheets."); setSheetName(first); const incoming = XLSX.utils.sheet_to_json<Record<string, unknown>>(workbook.Sheets[first], { defval: "", raw: false }).map(normalizeChangeRequestImportRow); if (!incoming.length) throw new Error("The worksheet has no Change Request references."); setRows(incoming); } catch (cause) { setRows([]); setMessage(cause instanceof Error ? cause.message : "The workbook could not be read."); } }
  async function call(mode: "preview" | "apply") { setBusy(true); setMessage(""); try { const response = await fetch("/api/changes/import", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode, fileName, sheetName, rows }) }); const payload = await response.json() as { preview?: ChangeRequestImportPreview; error?: string }; if (payload.preview) setPreview(payload.preview); if (!response.ok) throw new Error(payload.error || "Import failed."); setMessage(mode === "apply" ? "External Change Request references refreshed. Government decisions and analysis were retained." : "Preview complete. Review changed and blocked rows."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Import failed."); } finally { setBusy(false); } }
  function template() { const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet([[...CHANGE_REQUEST_IMPORT_COLUMNS]]), "Change Requests"); XLSX.writeFile(workbook, "Change_Request_Reference_Import.xlsx"); }
  return <DomainPageShell title="Change Request Reference Import" subtitle="Refresh externally managed request identity and status without overwriting Government analysis." actions={<><Link className="ghost-button" href="/changes">Return to Change Requests</Link><button className="ghost-button" type="button" onClick={template}>Download template</button></>}>
    <section className="decision-principle"><strong>Import boundary</strong><span>This import updates external identity, status, owner, source locator, source-as-of date, and requested Release only. Government priority, funding decisions, consequences, effects, dependencies, Objectives, and acceptance are retained.</span></section>
    <section className="split-layout"><article className="domain-section"><span className="eyebrow">EXTERNAL SOURCE</span><h3>Select Change Request workbook</h3><label className="modal-field">Excel workbook<input type="file" accept=".xlsx,.xls" onChange={(event) => void chooseFile(event.target.files?.[0])} /></label>{fileName ? <p className="entity-meta">{fileName} · {sheetName} · {rows.length} records</p> : null}<button className="primary-button" disabled={!rows.length || busy} onClick={() => void call("preview")}>{busy ? "Processing…" : "Preview reconciliation"}</button></article><article className="domain-section"><span className="eyebrow">MATCH RULE</span><h3>External system + external ID</h3><ul><li>New reference: added with pending Government decision.</li><li>Existing reference: supplier-controlled fields refreshed.</li><li>Government analysis: never overwritten.</li><li>Unknown type or Release: blocked before apply.</li></ul></article></section>
    {preview ? <section className="domain-section"><div className="section-toolbar"><div><span className="eyebrow">RECONCILIATION</span><h3>Source changes before application</h3></div><button className="primary-button" disabled={!preview.canApply || busy} onClick={() => void call("apply")}>{preview.canApply ? "Apply reference refresh" : "Resolve blocking issues"}</button></div><section className="summary"><div className="metric"><span>Add</span><strong>{preview.added}</strong></div><div className="metric"><span>Change</span><strong>{preview.changed}</strong></div><div className="metric"><span>Unchanged</span><strong>{preview.unchanged}</strong></div><div className="metric"><span>Blocked</span><strong>{preview.blocked}</strong></div></section><div className="domain-table-wrap"><table><thead><tr><th>Row</th><th>Reference</th><th>Source</th><th>Disposition</th><th>Changes / issues</th></tr></thead><tbody>{preview.rows.map((item) => <tr key={`${item.key}:${item.rowNumber}`}><td>{item.rowNumber}</td><td><strong>{item.row.ExternalIdentifier}</strong><small>{item.row.Title}</small></td><td>{item.row.ExternalSystem}<small>{item.row.SourceAsOf}</small></td><td><span className={`status-pill status-${item.disposition}`}>{item.disposition}</span></td><td>{item.issues.length ? item.issues.map((issue) => <small className="error-copy" key={issue}>{issue}</small>) : item.changedFields.length ? item.changedFields.join(", ") : "No source changes"}</td></tr>)}</tbody></table></div></section> : null}
    {message ? <p className={message.includes("failed") || message.includes("required") ? "toast toast-error" : "toast"}>{message}</p> : null}
  </DomainPageShell>;
}

