"use client";

import { useMemo, useState } from "react";
import * as XLSX from "xlsx";
import Link from "../../components/app-link";
import { DomainPageShell } from "../../components/domain-shell";
import { useBaselineWorkspace } from "../../lib/baseline-client";
import { productDisplayName, text } from "../../lib/baseline-data";
import { useChangePortfolio } from "../../lib/change-client";
import { usePlatformPortfolio } from "../../lib/platform-client";
import { compareReleases, releaseNames } from "../../lib/release-analysis";

type ReportTab = "inventory" | "release" | "funding";

export default function ReportsPage() {
  const { rows } = useBaselineWorkspace();
  const { portfolio: platforms } = usePlatformPortfolio();
  const { portfolio: changes } = useChangePortfolio();
  const [tab, setTab] = useState<ReportTab>("inventory");
  const releases = releaseNames(rows);
  const [fromRelease, setFromRelease] = useState("");
  const [toRelease, setToRelease] = useState("");
  const effectiveTo = toRelease || releases.at(-1) || "";
  const effectiveFrom = fromRelease || releases.filter((item) => item !== effectiveTo).at(-1) || "";
  const platformByNode = new Map(platforms.platforms.filter((item) => item.configurationNodeId).map((item) => [item.configurationNodeId!, item]));
  const inventory = rows.map((row) => { const platform = row.__meta.configurationNodeId ? platformByNode.get(row.__meta.configurationNodeId) : undefined; return { Release: text(row.ReleaseName) || "Unassigned", Product: productDisplayName(row), Supplier: text(row.OEM) || "Unassigned", Platform: platform ? `${platform.code} · ${platform.name}` : "Platform not linked", Tier: text(row.Tier) || "Unassigned", Resource: text(row.Resource) || "Unassigned", Host: text(row.HW_Host) || "Unassigned", Runtime: [text(row.Containerized), text(row["Container Technology"])].filter(Boolean).join(" · ") || "Not reported", SourceKey: text(row["#"]) || "Not assigned" }; });
  const deltas = effectiveFrom && effectiveTo ? compareReleases(rows, effectiveFrom, effectiveTo) : [];
  const funding = useMemo(() => changes.requests.map((request) => { const effects = changes.effects.filter((effect) => effect.changeRequestId === request.id); const dependencies = changes.dependencies.filter((item) => item.predecessorRequestId === request.id || item.successorRequestId === request.id); return { Type: request.typeCode, ExternalID: request.externalIdentifier, Title: request.title, GovernmentPriority: request.governmentPriority, FundingDecision: request.decisionStatus, RequestedRelease: request.requestedReleaseName || "Unassigned", AffectedObjects: effects.length, Dependencies: dependencies.length, ConsequenceIfFunded: request.consequenceIfFunded || "", ConsequenceIfDeferred: request.consequenceIfDeferred || "", KnockOnEffects: request.knockOnEffects || "", Authority: request.decisionAuthority || "", Rationale: request.decisionRationale || "" }; }), [changes]);
  function exportReport() {
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(inventory), "WHAT-WHERE-WHEN");
    XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(deltas.map((item) => ({ FromRelease: effectiveFrom, ToRelease: effectiveTo, ChangeType: item.kind, Product: item.productName, Before: item.beforePlacement || "Not present", After: item.afterPlacement || "Not present", ChangedFields: item.changedFields.join(", ") }))), "Release Comparison");
    XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(funding), "Funding Portfolio");
    XLSX.writeFile(workbook, `JSF_Decision_Reports_${new Date().toISOString().slice(0, 10)}.xlsx`);
  }
  return <DomainPageShell title="Leadership Reports" subtitle="What is where, what changed, and which Change Requests need a decision." releaseScope={`${releases.length} releases`} actions={<><Link className="ghost-button" href="/briefs">Report archive</Link><button className="ghost-button" type="button" onClick={() => window.print()}>Print report</button><button className="primary-button" type="button" onClick={exportReport}>Export workbook</button></>}>
    <section className="decision-principle"><strong>Report basis</strong><span>Counts come from baseline records and recorded Platform and Change Request links. Each page shows the current active baseline.</span></section>
    <nav className="detail-tabs report-tabs" aria-label="Report views"><button className={tab === "inventory" ? "active" : ""} onClick={() => setTab("inventory")}>WHAT · WHERE · WHEN</button><button className={tab === "release" ? "active" : ""} onClick={() => setTab("release")}>Release change book</button><button className={tab === "funding" ? "active" : ""} onClick={() => setTab("funding")}>Funding portfolio</button></nav>
    {tab === "inventory" ? <section className="domain-section"><div className="section-toolbar"><div><span className="eyebrow">CONFIGURATION INVENTORY</span><h3>What is installed, where, and in which release</h3></div><span>{inventory.length} baseline records</span></div><div className="domain-table-wrap"><table><thead><tr><th>When</th><th>What</th><th>Where · Platform</th><th>Placement</th><th>Supplier</th><th>Source key</th></tr></thead><tbody>{inventory.map((item, index) => <tr key={`${item.Release}:${item.SourceKey}:${index}`}><td><Link href={`/releases/${encodeURIComponent(item.Release)}`}>{item.Release}</Link></td><td>{item.Product}</td><td>{item.Platform}</td><td>{item.Tier} / {item.Resource} / <span className="mono">{item.Host}</span></td><td>{item.Supplier}</td><td className="mono">{item.SourceKey}</td></tr>)}</tbody></table></div></section> : null}
    {tab === "release" ? <section className="domain-section"><div className="section-toolbar"><div><span className="eyebrow">AS-IS → TO-BE</span><h3>Explainable source-data differences</h3></div><label className="compare-select"><select value={effectiveFrom} onChange={(event) => setFromRelease(event.target.value)}>{releases.map((item) => <option key={item}>{item}</option>)}</select> → <select value={effectiveTo} onChange={(event) => setToRelease(event.target.value)}>{releases.map((item) => <option key={item}>{item}</option>)}</select></label></div><section className="summary"><div className="metric"><span>Total data changes</span><strong>{deltas.length}</strong><small>{effectiveFrom} → {effectiveTo}</small></div><div className="metric"><span>Additions</span><strong>{deltas.filter((item) => item.kind.includes("added")).length}</strong><small>Product or deployment</small></div><div className="metric"><span>Removals</span><strong>{deltas.filter((item) => item.kind.includes("removed")).length}</strong><small>Absence in target release</small></div><div className="metric"><span>Moves / modifications</span><strong>{deltas.filter((item) => item.kind === "deployment_moved" || item.kind === "configuration_changed").length}</strong><small>Placement or attributes</small></div></section><div className="domain-table-wrap"><table><thead><tr><th>Change</th><th>Product</th><th>Before</th><th>After</th><th>Changed fields</th><th>Linked requests</th></tr></thead><tbody>{deltas.map((item) => { const anchorKeys = new Set(item.anchorIds.map((anchor) => `${anchor.kind}:${anchor.id}`)); const linked = changes.effects.filter((effect) => anchorKeys.has(`${effect.subjectKind}:${effect.subjectId}`)); const requestIds = Array.from(new Set(linked.map((effect) => effect.changeRequestId))); return <tr key={item.id}><td><span className={`effect-action effect-${item.kind.includes("added") ? "add" : item.kind.includes("removed") ? "remove" : item.kind.includes("moved") ? "move" : "modify"}`}>{item.kind.replaceAll("_", " ")}</span></td><td>{item.productName}</td><td>{item.beforePlacement || "Not present"}</td><td>{item.afterPlacement || "Not present"}</td><td>{item.changedFields.join(", ") || "—"}</td><td>{requestIds.length ? requestIds.map((requestId) => { const request = changes.requests.find((candidate) => candidate.id === requestId); return <Link key={requestId} href={`/changes/${encodeURIComponent(requestId)}`}>{request?.externalIdentifier || requestId}</Link>; }) : "Unexplained"}</td></tr>; })}</tbody></table></div></section> : null}
    {tab === "funding" ? <section className="domain-section"><div className="section-toolbar"><div><span className="eyebrow">LEADERSHIP DECISION REGISTER</span><h3>Fund, defer, or decline the work—not the technical baseline</h3></div><Link href="/changes">Manage Change Requests</Link></div><div className="domain-table-wrap"><table><thead><tr><th>Priority</th><th>Request</th><th>Target</th><th>Decision</th><th>Consequence if deferred</th><th>Effects</th><th>Dependencies</th></tr></thead><tbody>{changes.requests.map((request) => { const row = funding.find((item) => item.ExternalID === request.externalIdentifier)!; return <tr key={request.id}><td><span className={`priority-badge priority-${request.governmentPriority}`}>{request.governmentPriority}</span></td><td><Link href={`/changes/${encodeURIComponent(request.id)}`}><strong>{request.externalIdentifier}</strong><br />{request.title}</Link></td><td>{request.requestedReleaseName || "Unassigned"}</td><td><span className={`decision-badge decision-${request.decisionStatus}`}>{request.decisionStatus}</span></td><td>{request.consequenceIfDeferred || "Not assessed"}</td><td>{row.AffectedObjects}</td><td>{row.Dependencies}</td></tr>; })}</tbody></table></div></section> : null}
  </DomainPageShell>;
}
