import { env } from "cloudflare:workers";
import { PROGRAM_ID, WORKSPACE_ID } from "./governance-server";
import type { ControlQueueItem, ControlSnapshot } from "./control-model";
type Database = typeof env.DB;
type CountRow = { count: number };
type SourceRow = { file_name: string; received_at: string; status: string; row_count: number; accepted_count: number; exception_count: number };

export async function controlSnapshot(db: Database): Promise<ControlSnapshot> {
  const today = new Date().toISOString().slice(0, 10);
  const horizon = new Date(Date.now() + 60 * 86400000).toISOString().slice(0, 10);
  const [source, active, voided, unreviewed, aliases, unmapped, pending, objectiveGapRows, milestoneRows, initiativeRows, workRows, releaseRows, callRows] = await Promise.all([
    db.prepare("SELECT file_name,received_at,status,row_count,accepted_count,exception_count FROM source_package WHERE program_id=? ORDER BY received_at DESC LIMIT 1").bind(PROGRAM_ID).first<SourceRow>(),
    db.prepare("SELECT COUNT(*) AS count FROM baseline_occurrence WHERE workspace_id=? AND lifecycle_status='active'").bind(WORKSPACE_ID).first<CountRow>(),
    db.prepare("SELECT COUNT(*) AS count FROM baseline_occurrence WHERE workspace_id=? AND lifecycle_status='voided'").bind(WORKSPACE_ID).first<CountRow>(),
    db.prepare("SELECT COUNT(*) AS count FROM baseline_occurrence bo LEFT JOIN source_occurrence_review_v2 rv ON rv.source_row_id=bo.source_row_id WHERE bo.workspace_id=? AND bo.lifecycle_status='active' AND (rv.status IS NULL OR rv.status<>'reviewed')").bind(WORKSPACE_ID).first<CountRow>(),
    db.prepare("SELECT COUNT(*) AS count FROM canonical_alias WHERE program_id=? AND status='accepted'").bind(PROGRAM_ID).first<CountRow>(),
    db.prepare("SELECT COUNT(*) AS count FROM baseline_occurrence bo LEFT JOIN platform_baseline_assignment a ON a.baseline_occurrence_id=bo.id AND a.assignment_role='primary' WHERE bo.workspace_id=? AND bo.lifecycle_status='active' AND a.id IS NULL").bind(WORKSPACE_ID).first<CountRow>(),
    db.prepare("SELECT id,external_identifier,title,government_priority FROM change_request WHERE program_id=? AND decision_status='pending' ORDER BY CASE government_priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 ELSE 3 END,updated_at DESC").bind(PROGRAM_ID).all<{ id: string; external_identifier: string; title: string; government_priority: string }>(),
    db.prepare(`SELECT o.id,o.external_identifier,o.title,
      (SELECT COUNT(*) FROM objective_effect_attribution a WHERE a.objective_id=o.id) AS effects,
      (SELECT COUNT(*) FROM requirement_trace r WHERE r.objective_id=o.id) AS requirements,
      (SELECT COUNT(*) FROM acceptance_criterion c WHERE c.objective_id=o.id) AS criteria
      FROM incumbent_objective o WHERE o.program_id=? AND o.status<>'cancelled' AND (NOT EXISTS (SELECT 1 FROM objective_effect_attribution a WHERE a.objective_id=o.id) OR NOT EXISTS (SELECT 1 FROM requirement_trace rt WHERE rt.objective_id=o.id) OR NOT EXISTS (SELECT 1 FROM acceptance_criterion ac WHERE ac.objective_id=o.id)) ORDER BY o.external_identifier`).bind(PROGRAM_ID).all<{ id: string; external_identifier: string; title: string; effects: number; requirements: number; criteria: number }>(),
    db.prepare("SELECT m.id,m.title,m.planned_date,m.status,i.id AS initiative_id,i.title AS initiative_title FROM initiative_milestone m JOIN initiative i ON i.id=m.initiative_id WHERE i.program_id=? AND (m.status IN ('at_risk','missed') OR (m.status='planned' AND m.planned_date<=?)) ORDER BY m.planned_date").bind(PROGRAM_ID, horizon).all<{ id: string; title: string; planned_date: string; status: string; initiative_id: string; initiative_title: string }>(),
    db.prepare("SELECT i.id,i.title,i.decision_ask,i.desired_outcome,i.target_date,(SELECT COUNT(*) FROM initiative_change_request l WHERE l.initiative_id=i.id) AS requests FROM initiative i WHERE i.program_id=? AND i.status<>'closed' AND (i.decision_ask IS NULL OR i.desired_outcome IS NULL OR NOT EXISTS (SELECT 1 FROM initiative_change_request l WHERE l.initiative_id=i.id)) ORDER BY i.updated_at DESC").bind(PROGRAM_ID).all<{ id: string; title: string; decision_ask: string | null; desired_outcome: string | null; target_date: string | null; requests: number }>(),
    db.prepare("SELECT w.id,w.wbs_code,w.title,w.status,w.due_date,i.id AS initiative_id,i.title AS initiative_title FROM work_package w JOIN initiative i ON i.id=w.initiative_id WHERE i.program_id=? AND (w.status='on_hold' OR (w.status<>'complete' AND w.due_date IS NOT NULL AND w.due_date<?)) ORDER BY w.due_date").bind(PROGRAM_ID, today).all<{ id: string; wbs_code: string; title: string; status: string; due_date: string | null; initiative_id: string; initiative_title: string }>(),
    db.prepare("SELECT r.id,r.name,COALESCE(p.state_role,'unclassified') AS state_role FROM release r LEFT JOIN release_profile p ON p.release_id=r.id WHERE r.program_id=? ORDER BY r.name").bind(PROGRAM_ID).all<{ id: string; name: string; state_role: string }>(),
    db.prepare("SELECT id,title,owner,due_date,action_items FROM governance_record WHERE program_id=? AND record_type='technical_call' AND status IN ('open','in_review') AND (action_items IS NOT NULL OR decision_ask IS NOT NULL OR due_date IS NOT NULL) ORDER BY CASE WHEN due_date IS NULL THEN 1 ELSE 0 END,due_date,updated_at DESC").bind(PROGRAM_ID).all<{ id: string; title: string; owner: string | null; due_date: string | null; action_items: string | null }>(),
  ]);
  const queues: ControlQueueItem[] = [];
  if (!source) queues.push({ id: "source-missing", severity: "blocker", category: "Baseline", title: "No working baseline loaded", detail: "Import the current A2O XLSX exchange file before analysis.", href: "/intake" });
  else if (source.exception_count) queues.push({ id: "source-exceptions", severity: "blocker", category: "Source", title: `${source.exception_count} import exceptions`, detail: `${source.file_name} contains records that were not accepted without review.`, href: "/intake" });
  if (Number(unreviewed?.count || 0)) queues.push({ id: "manual-review", severity: "action", category: "Baseline", title: `${unreviewed?.count} baseline records require review`, detail: "Complete or mark follow-up for the active source projection.", href: "/" });
  if (Number(unmapped?.count || 0)) queues.push({ id: "platform-map", severity: "warning", category: "Platform", title: `${unmapped?.count} records have no primary Platform`, detail: "Assign fielding locations before using WHAT / WHERE reporting.", href: "/platforms" });
  for (const release of releaseRows.results.filter((item) => item.state_role === "unclassified")) queues.push({ id: `release-${release.id}`, severity: "action", category: "Release", title: `${release.name} has no analytical state role`, detail: "Classify the release as historical, As-Is, To-Be, or reported.", href: "/platforms" });
  for (const request of pending.results) queues.push({ id: `change-${request.id}`, severity: request.government_priority === "critical" ? "blocker" : "action", category: "Funding", title: `${request.external_identifier} requires a decision`, detail: `${request.government_priority} priority · ${request.title}`, href: `/changes/${encodeURIComponent(request.id)}` });
  for (const objective of objectiveGapRows.results) { const missing = [!objective.effects && "effects", !objective.requirements && "requirements", !objective.criteria && "acceptance criteria"].filter(Boolean).join(", "); queues.push({ id: `objective-${objective.id}`, severity: "warning", category: "Objective", title: `${objective.external_identifier} is incomplete`, detail: `Missing ${missing}.`, href: `/objectives/${encodeURIComponent(objective.id)}` }); }
  for (const milestone of milestoneRows.results) queues.push({ id: `milestone-${milestone.id}`, severity: milestone.status === "missed" ? "blocker" : milestone.status === "at_risk" ? "warning" : "action", category: "Schedule", title: `${milestone.title} · ${milestone.status.replace("_", " ")}`, detail: `${milestone.initiative_title} · ${milestone.planned_date}`, href: `/initiatives/${encodeURIComponent(milestone.initiative_id)}` });
  for (const work of workRows.results) queues.push({ id: `work-${work.id}`, severity: work.status === "on_hold" ? "warning" : "blocker", category: "WBS", title: `${work.wbs_code} · ${work.title}`, detail: `${work.initiative_title} · ${work.status === "on_hold" ? "on hold" : `overdue ${work.due_date}`}`, href: "/delivery" });
  for (const call of callRows.results) queues.push({ id: `call-${call.id}`, severity: call.due_date && call.due_date < today ? "blocker" : call.due_date && call.due_date <= horizon ? "action" : "warning", category: "Call follow-up", title: call.title, detail: `${call.owner || "Owner unassigned"}${call.due_date ? ` · due ${call.due_date}` : " · due date not set"}${call.action_items ? ` · ${call.action_items}` : ""}`, href: `/evidence?record=${encodeURIComponent(call.id)}` });
  for (const initiative of initiativeRows.results) { const missing = [!initiative.decision_ask && "decision ask", !initiative.desired_outcome && "desired outcome", !initiative.requests && "linked Change Request"].filter(Boolean).join(", "); queues.push({ id: `initiative-${initiative.id}`, severity: "warning", category: "Initiative", title: `${initiative.title} is not briefing-ready`, detail: `Missing ${missing}.`, href: `/initiatives/${encodeURIComponent(initiative.id)}` }); }
  if (!queues.length) queues.push({ id: "ready", severity: "ready", category: "Control", title: "No open control items", detail: "The active prototype dataset passes the current control checks.", href: "/reports" });
  return { generatedAt: new Date().toISOString(), source: { fileName: source?.file_name || null, receivedAt: source?.received_at || null, status: source?.status || null, rowCount: Number(source?.row_count || 0), acceptedCount: Number(source?.accepted_count || 0), exceptionCount: Number(source?.exception_count || 0) }, counts: { activeRecords: Number(active?.count || 0), voidedRecords: Number(voided?.count || 0), unreviewedRecords: Number(unreviewed?.count || 0), acceptedAliases: Number(aliases?.count || 0), unmappedPlatforms: Number(unmapped?.count || 0), pendingDecisions: pending.results.length, objectiveGaps: objectiveGapRows.results.length, deliveryRisks: milestoneRows.results.length + workRows.results.length, initiativeGaps: initiativeRows.results.length, callActions: callRows.results.length }, queues };
}
