"use client";

import { useMemo, useState } from "react";
import { useParams } from "next/navigation";
import Link from "../../../../components/app-link";
import { useGovernancePortfolio } from "../../../../lib/governance-client";
import { useInitiativeDecisions } from "../../../../lib/initiative-decision-client";
import { objectiveIsRelatedToChangeRequest, readable, selectInitiativeBundle, tierLabel } from "../../../../lib/initiative-decision-model";
import { criterionIsAccepted, estimateVariance } from "../../../../lib/initiative-readiness";
import { dependencyStatement } from "../../../../lib/change-model";
import { deriveInitiativeScope } from "../../../../lib/initiative-scope";
import { informationOriginLabel, informationStatusSummary } from "../../../../lib/information-status";

const dateLabel = (value: string | null) => value ? new Date(`${value.slice(0, 10)}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) : "Not set";
const dateTimeLabel = (value: string) => new Date(value).toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" });
const compact = (value: number | null | undefined, prefix = "") => value !== null && value !== undefined && Number.isFinite(value) ? `${prefix}${new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(value)}` : "Not assessed";
const estimateText = (estimate: { hoursLikely: number | null; costLikely: number | null; romPointsLikely?: number | null; asOf: string; confidence: string }, hoursPerPoint: number) => estimate.romPointsLikely !== null && estimate.romPointsLikely !== undefined
  ? `${compact(estimate.romPointsLikely)} Lockheed ROM points → ${compact(estimate.romPointsLikely * hoursPerPoint)} planning h (${estimate.asOf}; ${readable(estimate.confidence)})`
  : `${compact(estimate.hoursLikely)}${estimate.hoursLikely === null ? "" : " h"} / ${compact(estimate.costLikely, "$")} (${estimate.asOf}; ${readable(estimate.confidence)})`;
const wallText = (value: string | null | undefined, maximum: number, fallback: string) => {
  const normalized = value?.trim() || fallback;
  return normalized.length > maximum ? `${normalized.slice(0, Math.max(0, maximum - 1)).trimEnd()}…` : normalized;
};

export default function InitiativeOnePager() {
  const params = useParams<{ initiative?: string }>();
  const initiativeId = decodeURIComponent(params.initiative || "");
  const { workspace, loading, error } = useInitiativeDecisions(initiativeId);
  const { portfolio, loading: governanceLoading, error: governanceError } = useGovernancePortfolio();
  const [printMode, setPrintMode] = useState<"one" | "four">("one");
  const [generatedAt] = useState(() => new Date().toISOString());
  const bundle = useMemo(() => workspace ? selectInitiativeBundle(workspace, initiativeId) : null, [workspace, initiativeId]);
  const assessment = workspace?.assessments[initiativeId];
  const initiativeRecords = useMemo(() => portfolio?.records.filter((record) => record.links.some((link) => link.entityKind === "initiative" && link.entityId === initiativeId)) || [], [portfolio?.records, initiativeId]);
  const initiativeDocuments = useMemo(() => {
    const documents = new Map<string, NonNullable<typeof portfolio>["documents"][number]>();
    for (const document of portfolio?.documents || []) if (document.initiativeId === initiativeId && !document.quarantined && document.integritySealed) documents.set(document.id, document);
    for (const record of initiativeRecords) for (const document of record.documents) if (!document.quarantined && document.integritySealed) documents.set(document.id, document);
    const portfolioById = new Map((portfolio?.documents || []).map((document) => [document.id, document]));
    for (const criterion of bundle?.criteria || []) for (const signoff of criterion.signoffs) {
      const document = signoff.evidenceDocumentId ? portfolioById.get(signoff.evidenceDocumentId) : null;
      if (document && signoff.evidenceIntegrityStatus === "verified" && !document.quarantined && document.integritySealed) documents.set(document.id, document);
    }
    return [...documents.values()].sort((left, right) => right.createdAt.localeCompare(left.createdAt));
  }, [portfolio?.documents, initiativeId, initiativeRecords, bundle]);
  if (loading || governanceLoading) return <main className="one-pager-loading">Preparing report…</main>;
  if (error || governanceError || !bundle || !portfolio) return <main className="one-pager-loading"><p>{error || governanceError || "Initiative not found."}</p><Link href="/initiatives">Back to Initiatives</Link></main>;
  const initiative = bundle.initiative;
  const handlingMarking = portfolio.handlingMarking;
  const variance = estimateVariance(bundle);
  const derivedScope = deriveInitiativeScope(bundle);
  const pendingCriteria = bundle.criteria.filter((criterion) => !criterionIsAccepted(criterion));
  const acceptedCriteria = bundle.criteria.filter(criterionIsAccepted);
  const keyFindings = assessment?.findings.filter((item) => item.severity !== "information").slice(0, 6) || [];
  const requestIds = new Set(bundle.changeRequests.map((request) => request.id));
  const relevantDependencies = bundle.changes.dependencies.filter((item) => requestIds.has(item.predecessorRequestId) || requestIds.has(item.successorRequestId));
  const requestById = new Map(bundle.changes.requests.map((request) => [request.id, request]));
  const relevantEffects = bundle.changes.effects.filter((effect) => requestIds.has(effect.changeRequestId));
  const relevantEffectById = new Map(relevantEffects.map((effect) => [effect.id, effect]));
  const attributedEffectsByObjective = new Map<string, NonNullable<typeof bundle.objectiveEffectAttributions>>();
  for (const attribution of bundle.objectiveEffectAttributions || []) {
    if (!relevantEffectById.has(attribution.changeEffectId)) continue;
    const current = attributedEffectsByObjective.get(attribution.objectiveId) || [];
    current.push(attribution);
    attributedEffectsByObjective.set(attribution.objectiveId, current);
  }
  const dataLastChangedAt = [initiative.updatedAt, ...bundle.changeRequests.map((item) => item.updatedAt), ...bundle.objectives.map((item) => item.updatedAt), ...bundle.objectives.flatMap((item) => item.estimates.map((estimate) => estimate.createdAt)), ...(bundle.objectiveChangeRequestLinks ?? []).map((item) => item.updatedAt), ...(bundle.objectiveDependencies ?? []).map((item) => item.updatedAt), ...(bundle.objectiveEffectAttributions ?? []).map((item) => item.updatedAt), ...bundle.changes.dependencies.map((item) => item.sourceAsOf), ...bundle.requirements.map((item) => item.updatedAt), ...bundle.criteria.map((item) => item.updatedAt), ...bundle.criteria.flatMap((item) => item.signoffs.map((signoff) => signoff.updatedAt)), ...bundle.milestones.map((item) => item.updatedAt), ...initiativeRecords.map((item) => item.updatedAt), ...initiativeDocuments.map((item) => item.createdAt), ...portfolio.activity.map((item) => item.createdAt)].filter((item): item is string => Boolean(item)).sort((left, right) => right.localeCompare(left))[0] || generatedAt;
  const omittedItems = Math.max(0, bundle.changeRequests.length - 4) + Math.max(0, bundle.milestones.length - 7) + Math.max(0, bundle.criteria.length - 6) + Math.max(0, (assessment?.findings.filter((item) => item.severity !== "information").length || 0) - 6);
  const wallTextLimits: Array<[string | null | undefined, number]> = [
    [initiative.title, 110], [initiative.briefingAudience, 90], [initiative.asIsStatement, 560], [initiative.toBeStatement, 560],
    [initiative.decisionAsk, 240], [initiative.desiredOutcome, 190], [initiative.consequence, 190], [initiative.successMeasures, 65],
    ...bundle.changeRequests.slice(0, 4).flatMap((request) => [[request.title, 85], [request.impactSummary || request.summary, 150]] as Array<[string | null | undefined, number]>),
    ...bundle.milestones.slice(0, 7).map((milestone) => [milestone.title, 48] as [string | null | undefined, number]),
    ...bundle.criteria.slice(0, 6).flatMap((criterion) => [[criterion.statement, 120], [criterion.evidenceReference, 70]] as Array<[string | null | undefined, number]>),
    ...keyFindings.flatMap((finding) => [[finding.title, 55], [finding.detail, 100]] as Array<[string | null | undefined, number]>),
  ];
  const truncatedWallItems = wallTextLimits.filter(([value, maximum]) => (value?.trim().length || 0) > maximum).length;
  const requiresAnnex = omittedItems > 0 || truncatedWallItems > 0;
  const unacceptableEvidence = bundle.criteria.flatMap((criterion) => ["passed", "waived"].includes(criterion.status)
    ? criterion.signoffs.filter((signoff) => ["accepted", "waived"].includes(signoff.decision) && Boolean(signoff.evidenceDocumentId) && signoff.evidenceIntegrityStatus !== "verified")
    : []);
  const printBlockReason = unacceptableEvidence.length
    ? `${unacceptableEvidence.length} completed acceptance sign-off${unacceptableEvidence.length === 1 ? " has" : "s have"} evidence that is missing, unverified, or outside the current verification envelope. Repair or re-verify it before printing.`
    : "";
  return <main className={`initiative-one-pager ${printMode === "four" ? "four-page-packet" : ""}`}>
    <div className="one-pager-actions"><Link href={`/initiatives/${encodeURIComponent(initiativeId)}`}>← Return to analysis</Link>{printBlockReason ? <span className="one-pager-content-warning" role="alert">{printBlockReason}</span> : requiresAnnex && printMode === "one" ? <span className="one-pager-content-warning">The one-page brief is deliberately bounded; omitted detail is identified in the four-page packet and governed report snapshot.</span> : null}<label><input type="radio" name="initiative-print-mode" checked={printMode === "one"} onChange={() => setPrintMode("one")} /> One-page decision brief</label><label><input type="radio" name="initiative-print-mode" checked={printMode === "four"} onChange={() => setPrintMode("four")} /> Four-page detail packet</label><button type="button" disabled={Boolean(printBlockReason)} title={printBlockReason || `Print the ${printMode === "four" ? "four-page detail packet" : "one-page decision brief"}`} onClick={() => window.print()}>{printMode === "four" ? "Print / Save 4 pages" : "Print / Save 1 page"}</button></div>
    <article className="wall-sheet">
      <div className="output-handling-banner">{handlingMarking}</div>
      <header className="wall-header"><div><span>JSF TECHNICAL BASELINE · DECISION SUPPORT DRAFT</span><h1>{wallText(initiative.title, 110, "Untitled Initiative")}</h1><p>{wallText(initiative.briefingAudience, 90, "Leadership audience not recorded")} · Generated {dateTimeLabel(generatedAt)} · Data through {dateTimeLabel(dataLastChangedAt)}</p></div><div className={`readiness-seal readiness-${assessment?.stage || "not_ready"}`}><strong>{assessment?.score || 0}%</strong><span>{readable(assessment?.stage || "not_ready")}</span></div></header>
      <section className="wall-state-row"><article><span>LEFT · WHERE WE ARE</span><h2>As-Is</h2><p>{wallText(initiative.asIsStatement, 560, "Current state is not yet substantiated.")}</p></article><div className="wall-change-path"><strong>{bundle.changeRequests.length}</strong><span>Change Requests</span><b>→</b><small>{bundle.objectives.length} Objectives · {derivedScope.affectedObjects.length} affected objects · {derivedScope.explicitBaselineRecordCount} explicit baseline records</small></div><article><span>RIGHT · WHERE WE NEED TO BE</span><h2>To-Be</h2><p>{wallText(initiative.toBeStatement, 560, "Target state is not yet defined.")}</p></article></section>
      <section className="wall-decision-row"><article className="wall-decision-ask"><span>THE DECISION</span><h2>{wallText(initiative.decisionAsk, 240, "Decision ask has not been recorded.")}</h2><p><strong>Needed by:</strong> {dateLabel(initiative.decisionNeededBy)} · <strong>Outcome target:</strong> {dateLabel(initiative.targetDate)}</p></article><article><span>IF FUNDED / DIRECTED</span><p>{wallText(initiative.desiredOutcome, 190, "Desired outcome not recorded.")}</p></article><article className="wall-consequence"><span>IF DEFERRED</span><p>{wallText(initiative.consequence, 190, "Consequence not recorded.")}</p></article></section>
      <section className="wall-main-grid"><article className="wall-panel wall-crs"><header><span>HOW WE GET THERE</span><strong>{assessment?.decisionsPending || 0} decisions pending</strong></header>{bundle.changeRequests.slice(0, 4).map((request, index) => { const objectiveCount = bundle.objectives.filter((item) => objectiveIsRelatedToChangeRequest(item, request.id, bundle.objectiveChangeRequestLinks)).length; return <div className="wall-cr" key={request.id}><b>{index + 1}</b><div><strong>{request.externalIdentifier} · {wallText(request.title, 85, "Untitled request")}</strong><p>{wallText(request.impactSummary || request.summary, 150, "Impact analysis missing.")}</p><small>{objectiveCount} Objectives · {request.requestedReleaseName || "No target release"}</small></div><span className={`wall-status wall-status-${request.decisionStatus}`}>{readable(request.decisionStatus)}</span></div>; })}{bundle.changeRequests.length > 4 ? <p className="wall-omission">+ {bundle.changeRequests.length - 4} additional Change Requests in the annex</p> : null}</article>
        <article className="wall-panel wall-timeline"><header><span>WHEN</span><strong>Delivery timeline</strong></header>{bundle.milestones.slice(0, 7).map((milestone) => <div className="wall-milestone" key={milestone.id}><time>{dateLabel(milestone.plannedDate)}</time><i className={`milestone-dot milestone-${milestone.status}`} /><div><strong>{wallText(milestone.title, 48, "Untitled milestone")}</strong><small>{readable(milestone.milestoneType)} · {readable(milestone.status)}</small></div></div>)}{!bundle.milestones.length && <p>No milestones recorded.</p>}</article>
        <article className="wall-panel wall-analysis"><header><span>ANALYSIS CHECK</span><strong>Claims vs assessment</strong></header><div className="wall-estimates"><div><span>Incumbent likely hours</span><strong>{compact(variance.incumbentHours)}</strong><small>{compact(variance.incumbentCost, "$")} · {Math.max(variance.incumbentHoursCoverage, variance.incumbentCostCoverage)}/{variance.objectiveCount} Objectives</small></div><div><span>Gov./independent hours</span><strong>{compact(variance.assessedHours)}</strong><small>{compact(variance.assessedCost, "$")} · {Math.max(variance.assessedHoursCoverage, variance.assessedCostCoverage)}/{variance.objectiveCount} Objectives</small></div></div>{variance.incumbentRomPoints !== null ? <p className="wall-fineprint">Lockheed source: {compact(variance.incumbentRomPoints)} ROM points × {compact(variance.romHoursPerPoint)} h/point = {compact(variance.incumbentRomPoints * variance.romHoursPerPoint)} planning h.</p> : null}<div className="wall-trace"><span>{bundle.requirements.filter((item) => ["traced", "verified", "not_applicable"].includes(item.traceStatus)).length}/{bundle.requirements.length} requirements traced</span><span>{acceptedCriteria.length}/{bundle.criteria.length} criteria accepted</span></div><p className="wall-fineprint">Converted hours are an Initiative-level Government planning assumption. Totals are not program-approved cost.</p></article>
      </section>
      <section className="wall-bottom-grid"><article className="wall-panel"><header><span>REQUIREMENTS & ACCEPTANCE</span><strong>{pendingCriteria.length} open criteria</strong></header><div className="wall-criteria">{bundle.criteria.slice(0, 6).map((criterion) => <div key={criterion.id}><strong>{tierLabel(criterion.tier)} · {criterion.code}</strong><p>{wallText(criterion.statement, 120, "Acceptance statement not recorded")}</p><small>{readable(criterion.status)} · {wallText(criterion.evidenceReference, 70, "Evidence pending")}</small></div>)}</div></article><article className="wall-panel wall-risks"><header><span>GAPS / KNOCK-ON EFFECTS</span><strong>{assessment?.blockers || 0} blockers · {assessment?.warnings || 0} warnings</strong></header>{keyFindings.map((finding) => <div key={finding.id}><b>{finding.severity === "blocker" ? "!" : "△"}</b><p><strong>{wallText(finding.title, 55, "Readiness finding")}</strong><span>{wallText(finding.detail, 100, "Detail not recorded")}</span></p></div>)}{!keyFindings.length && <p>No automated evidence-chain gaps detected.</p>}</article></section>
      <footer className="wall-footer"><span>{handlingMarking}</span><span>Owner: {initiative.owner || "Unassigned"}</span><span>Success: {wallText(initiative.successMeasures, 65, "Measures not recorded")}</span><span>Sources: {initiativeDocuments.length} attached documents, baseline records, Government assessments, and referenced external systems{omittedItems ? ` · ${omittedItems} detail items continue in the four-page packet` : ""}</span></footer>
    </article>
    {printMode === "four" ? <>
      <article className="detail-packet-page packet-page-two">
        <div className="output-handling-banner">{handlingMarking}</div>
        <header className="packet-header"><div><span>JSF TECHNICAL BASELINE · DETAIL PACKET · PAGE 2 OF 4</span><h1>{initiative.title}</h1><p>Decision narrative, Change Requests, and dependencies · Data through {dateTimeLabel(dataLastChangedAt)}</p></div><strong>{assessment?.score || 0}%<small>{readable(assessment?.stage || "not_ready")}</small></strong></header>
        <section className="packet-narrative"><article><span>DECISION</span><p>{wallText(initiative.decisionAsk, 330, "Not recorded")}</p></article><article><span>AS-IS</span><p>{wallText(initiative.asIsStatement, 330, "Not recorded")}</p></article><article><span>TO-BE</span><p>{wallText(initiative.toBeStatement || initiative.desiredOutcome, 330, "Not recorded")}</p></article><article><span>IF DEFERRED</span><p>{wallText(initiative.consequence, 250, "Not recorded")}</p></article></section>
        <section className="packet-section"><h2>External Change Request references</h2><table><thead><tr><th>Reference / analysis</th><th>External system / status</th><th>Source checked</th><th>Government decision</th></tr></thead><tbody>{bundle.changeRequests.slice(0, 6).map((request) => <tr key={request.id}><td>{request.externalIdentifier}<small>{wallText(request.title, 105, "Untitled request")}</small><small>{wallText(request.impactSummary || request.summary, 145, "Impact analysis not recorded")}</small></td><td>{request.externalSystem || "Not recorded"}<small>{request.externalStatus || "External status not recorded"}</small></td><td>{request.sourceAsOf || "Not recorded"}<small>{wallText(request.sourceLocator, 70, "Locator not recorded")}</small></td><td>{readable(request.decisionStatus)}<small>{request.decisionAuthority || "Authority not recorded"}</small></td></tr>)}{bundle.changeRequests.length > 6 ? <tr><td colSpan={4}>+ {bundle.changeRequests.length - 6} additional Change Requests remain in the Initiative workspace and governed report snapshot.</td></tr> : null}</tbody></table></section>
        <section className="packet-section"><h2>Governed dependency narrative</h2><table><thead><tr><th>Dependency statement</th><th>Basis</th><th>Consequence if unmet</th><th>Confidence / source</th></tr></thead><tbody>{relevantDependencies.slice(0, 5).map((dependency) => { const predecessor = requestById.get(dependency.predecessorRequestId)?.externalIdentifier || dependency.predecessorRequestId; const successor = requestById.get(dependency.successorRequestId)?.externalIdentifier || dependency.successorRequestId; return <tr key={dependency.id}><td>{dependencyStatement(dependency, predecessor, successor)}</td><td>{wallText(dependency.rationale, 130, "Not recorded")}</td><td>{wallText(dependency.consequenceIfUnmet, 130, "Not assessed")}</td><td>{readable(dependency.confidence)}<small>{wallText(dependency.sourceReference, 75, "Source not recorded")}{dependency.sourceAsOf ? ` · ${dependency.sourceAsOf}` : ""}</small></td></tr>; })}{!relevantDependencies.length ? <tr><td colSpan={4}>No Change Request dependencies are recorded for this Initiative.</td></tr> : relevantDependencies.length > 5 ? <tr><td colSpan={4}>+ {relevantDependencies.length - 5} additional dependencies remain in the Initiative workspace and governed report snapshot.</td></tr> : null}</tbody></table></section>
        <footer className="packet-footer"><span>{handlingMarking}</span><span>Page 2 of 4 · Bounded detail packet; the Initiative workspace and saved report retain the complete governed record.</span></footer>
      </article>
      <article className="detail-packet-page packet-page-three">
        <div className="output-handling-banner">{handlingMarking}</div>
        <header className="packet-header"><div><span>JSF TECHNICAL BASELINE · DETAIL PACKET · PAGE 3 OF 4</span><h1>{initiative.title}</h1><p>Affected objects, delivery Objectives, requirements, and acceptance</p></div><strong>{derivedScope.affectedObjects.length}<small>affected objects</small></strong></header>
        <section className="packet-section"><h2>Affected technical objects</h2><table><thead><tr><th>Change Request</th><th>Action / object</th><th>State transition</th><th>Release effect</th></tr></thead><tbody>{relevantEffects.slice(0, 6).map((effect) => <tr key={effect.id}><td>{requestById.get(effect.changeRequestId)?.externalIdentifier || effect.changeRequestId}</td><td>{readable(effect.action)} {readable(effect.subjectKind)}<small>{wallText(`${effect.subjectLabel} · ${effect.aspect}`, 120, "Not recorded")}</small></td><td>{wallText(`${effect.currentValue || "Not reported"} → ${effect.targetValue || "Not reported"}`, 110, "Not reported")}<small>{wallText(effect.consequence, 90, "Consequence not assessed")}</small></td><td>{effect.fromReleaseName || "Current / unspecified"} → {effect.toReleaseName || "Target / unspecified"}</td></tr>)}{!relevantEffects.length ? <tr><td colSpan={4}>No affected technical objects are linked.</td></tr> : relevantEffects.length > 6 ? <tr><td colSpan={4}>+ {relevantEffects.length - 6} additional affected objects remain in the Initiative workspace and governed report snapshot.</td></tr> : null}</tbody></table></section>
        <section className="packet-section"><h2>Objective delivery and sourced estimates</h2><table><thead><tr><th>Objective</th><th>Schedule / status</th><th>Scoped effects / attribution</th><th>Sourced estimate</th></tr></thead><tbody>{bundle.objectives.slice(0, 6).map((objective) => { const attributions = attributedEffectsByObjective.get(objective.id) || []; return <tr key={objective.id}><td>{objective.externalIdentifier}<small>{wallText(objective.title, 115, "Untitled Objective")}</small></td><td>{dateLabel(objective.plannedStart)} → {dateLabel(objective.plannedFinish)}<small>{readable(objective.status)}</small></td><td>{attributions.length ? attributions.slice(0, 2).map((attribution) => { const effect = relevantEffectById.get(attribution.changeEffectId); return <small key={attribution.id}>{readable(attribution.attribution)} · {wallText(effect?.subjectLabel, 65, attribution.changeEffectId)}</small>; }) : "No attributed effect"}</td><td>{objective.estimates.length ? objective.estimates.slice(0, 2).map((estimate) => `${readable(estimate.estimateSource)}: ${estimateText(estimate, initiative.romHoursPerPoint)}`).join("; ") : "No sourced estimate"}</td></tr>; })}{bundle.objectives.length > 6 ? <tr><td colSpan={4}>+ {bundle.objectives.length - 6} additional Objectives remain in the Initiative workspace and governed report snapshot.</td></tr> : null}</tbody></table></section>
        <section className="packet-split"><div><h2>Requirement trace</h2>{bundle.requirements.slice(0, 4).map((requirement) => <p key={requirement.id}><strong>{requirement.externalIdentifier}</strong> · {readable(requirement.traceStatus)}<small>{wallText(requirement.title, 110, "Untitled requirement")}</small></p>)}{bundle.requirements.length > 4 ? <p>+ {bundle.requirements.length - 4} more traces in the Initiative workspace and governed report snapshot.</p> : null}{!bundle.requirements.length ? <p>No requirement traces are linked.</p> : null}</div><div><h2>Acceptance</h2>{bundle.criteria.slice(0, 4).map((criterion) => <p key={criterion.id}><strong>{tierLabel(criterion.tier)} · {criterion.code}</strong> · {readable(criterion.status)}<small>{wallText(criterion.statement, 130, "Acceptance statement not recorded")}</small></p>)}{bundle.criteria.length > 4 ? <p>+ {bundle.criteria.length - 4} more criteria in the Initiative workspace and governed report snapshot.</p> : null}{!bundle.criteria.length ? <p>No acceptance criteria are linked.</p> : null}</div></section>
        <footer className="packet-footer"><span>{handlingMarking}</span><span>Page 3 of 4 · Supplier-reported source, Government assessment, and acceptance remain visibly distinct.</span></footer>
      </article>
      <article className="detail-packet-page packet-page-four">
        <div className="output-handling-banner">{handlingMarking}</div>
        <header className="packet-header"><div><span>JSF TECHNICAL BASELINE · DETAIL PACKET · PAGE 4 OF 4</span><h1>{initiative.title}</h1><p>Execution outlook, readiness findings, linked records, and evidence</p></div><strong>{assessment?.blockers || 0}<small>blockers</small></strong></header>
        <section className="packet-section"><h2>Milestones and readiness findings</h2><table><thead><tr><th>Date / subject</th><th>Status / severity</th><th>Detail</th></tr></thead><tbody>{bundle.milestones.slice(0, 6).map((milestone) => <tr key={milestone.id}><td>{dateLabel(milestone.plannedDate)}<small>{wallText(milestone.title, 105, "Untitled milestone")}</small></td><td>{readable(milestone.status)}</td><td>{wallText(milestone.consequenceIfMissed, 175, "No downstream consequence recorded")}</td></tr>)}{(assessment?.findings || []).slice(0, 5).map((finding) => <tr key={finding.id}><td>{wallText(finding.title, 105, "Readiness finding")}</td><td>{readable(finding.severity)}</td><td>{wallText(finding.detail, 175, "Detail not recorded")}</td></tr>)}{bundle.milestones.length > 6 || (assessment?.findings.length || 0) > 5 ? <tr><td colSpan={3}>Additional milestones or findings remain in the Initiative workspace and governed report snapshot.</td></tr> : null}</tbody></table></section>
        <section className="packet-split"><div><h2>Linked calls, decisions, and risks</h2>{initiativeRecords.slice(0, 5).map((record) => <p key={record.id}><strong>{readable(record.recordType)} · {wallText(record.title, 100, "Untitled record")}</strong><small>{informationOriginLabel(record.informationOrigin)} · {readable(record.status)} · {record.occurredAt ? dateLabel(record.occurredAt) : "Date not recorded"}</small><small>{wallText(record.summary, 155, "No summary recorded")}</small></p>)}{initiativeRecords.length > 5 ? <p>+ {initiativeRecords.length - 5} more records in the Initiative workspace and governed report snapshot.</p> : null}{!initiativeRecords.length ? <p>No linked calls, decisions, risks, questions, or technical notes are recorded.</p> : null}</div><div><h2>Supporting documents</h2>{initiativeDocuments.slice(0, 5).map((document) => <p key={document.id}><strong>{wallText(document.fileName, 100, "Untitled document")}</strong><small>{wallText(document.description, 155, "What it substantiates is not described")}</small><small>Attached {dateTimeLabel(document.createdAt)}</small></p>)}{initiativeDocuments.length > 5 ? <p>+ {initiativeDocuments.length - 5} more documents in the Initiative workspace and governed report snapshot.</p> : null}{!initiativeDocuments.length ? <p>No supporting documents are attached to this Initiative.</p> : null}</div></section>
        <section className="packet-information"><strong>Information status:</strong> {informationStatusSummary}</section>
        <footer className="packet-footer"><span>{handlingMarking}</span><span>Page 4 of 4 · Generated from the governed application dataset. External Change Requests remain controlled in their originating system.</span></footer>
      </article>
    </> : null}
  </main>;
}
