"use client";

import { useMemo, useState } from "react";
import { useParams } from "next/navigation";
import Link from "../../../../components/app-link";
import { useGovernancePortfolio } from "../../../../lib/governance-client";
import { useInitiativeDecisions } from "../../../../lib/initiative-decision-client";
import { objectiveIsRelatedToChangeRequest, readable, selectInitiativeBundle, tierLabel } from "../../../../lib/initiative-decision-model";
import { criterionIsAccepted, estimateVariance } from "../../../../lib/initiative-readiness";
import { dependencyStatement } from "../../../../lib/change-model";

const dateLabel = (value: string | null) => value ? new Date(`${value.slice(0, 10)}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) : "Not set";
const dateTimeLabel = (value: string) => new Date(value).toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" });
const compact = (value: number | null | undefined, prefix = "") => value !== null && value !== undefined && Number.isFinite(value) ? `${prefix}${new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(value)}` : "Not assessed";
const wallText = (value: string | null | undefined, maximum: number, fallback: string) => {
  const normalized = value?.trim() || fallback;
  return normalized.length > maximum ? `${normalized.slice(0, Math.max(0, maximum - 1)).trimEnd()}…` : normalized;
};

export default function InitiativeOnePager() {
  const params = useParams<{ initiative?: string }>();
  const initiativeId = decodeURIComponent(params.initiative || "");
  const { workspace, loading, error } = useInitiativeDecisions(initiativeId);
  const { portfolio, loading: governanceLoading, error: governanceError } = useGovernancePortfolio();
  const [includeAnnex, setIncludeAnnex] = useState(false);
  const [generatedAt] = useState(() => new Date().toISOString());
  const bundle = useMemo(() => workspace ? selectInitiativeBundle(workspace, initiativeId) : null, [workspace, initiativeId]);
  const assessment = workspace?.assessments[initiativeId];
  const initiativeRecords = useMemo(() => portfolio?.records.filter((record) => record.links.some((link) => link.entityKind === "initiative" && link.entityId === initiativeId)) || [], [portfolio?.records, initiativeId]);
  const initiativeDocuments = useMemo(() => {
    const documents = new Map<string, NonNullable<typeof portfolio>["documents"][number]>();
    for (const document of portfolio?.documents || []) if (document.initiativeId === initiativeId && !document.quarantined && document.integritySealed) documents.set(document.id, document);
    for (const record of initiativeRecords) for (const document of record.documents) if (!document.quarantined && document.integritySealed) documents.set(document.id, document);
    const portfolioById = new Map((portfolio?.documents || []).map((document) => [document.id, document]));
    for (const criterion of bundle?.criteria || []) for (const signoff of criterion.signoffs) {
      const document = signoff.evidenceDocumentId ? portfolioById.get(signoff.evidenceDocumentId) : null;
      if (document && signoff.evidenceIntegrityStatus === "verified" && !document.quarantined && document.integritySealed) documents.set(document.id, document);
    }
    return [...documents.values()].sort((left, right) => right.createdAt.localeCompare(left.createdAt));
  }, [portfolio?.documents, initiativeId, initiativeRecords, bundle]);
  if (loading || governanceLoading) return <main className="one-pager-loading">Preparing report…</main>;
  if (error || governanceError || !bundle || !portfolio) return <main className="one-pager-loading"><p>{error || governanceError || "Initiative not found."}</p><Link href="/initiatives">Back to Initiatives</Link></main>;
  const initiative = bundle.initiative;
  const handlingMarking = portfolio.handlingMarking;
  const variance = estimateVariance(bundle);
  const effectCount = bundle.changes.effects.filter((effect) => bundle.changeRequests.some((request) => request.id === effect.changeRequestId)).length;
  const pendingCriteria = bundle.criteria.filter((criterion) => !criterionIsAccepted(criterion));
  const acceptedCriteria = bundle.criteria.filter(criterionIsAccepted);
  const keyFindings = assessment?.findings.filter((item) => item.severity !== "information").slice(0, 6) || [];
  const requestIds = new Set(bundle.changeRequests.map((request) => request.id));
  const relevantDependencies = bundle.changes.dependencies.filter((item) => requestIds.has(item.predecessorRequestId) || requestIds.has(item.successorRequestId));
  const requestById = new Map(bundle.changes.requests.map((request) => [request.id, request]));
  const relevantEffects = bundle.changes.effects.filter((effect) => requestIds.has(effect.changeRequestId));
  const dataLastChangedAt = [initiative.updatedAt, ...bundle.changeRequests.map((item) => item.updatedAt), ...bundle.objectives.map((item) => item.updatedAt), ...bundle.objectives.flatMap((item) => item.estimates.map((estimate) => estimate.createdAt)), ...(bundle.objectiveChangeRequestLinks ?? []).map((item) => item.updatedAt), ...(bundle.objectiveDependencies ?? []).map((item) => item.updatedAt), ...(bundle.objectiveEffectAttributions ?? []).map((item) => item.updatedAt), ...bundle.changes.dependencies.map((item) => item.sourceAsOf), ...bundle.requirements.map((item) => item.updatedAt), ...bundle.criteria.map((item) => item.updatedAt), ...bundle.criteria.flatMap((item) => item.signoffs.map((signoff) => signoff.updatedAt)), ...bundle.milestones.map((item) => item.updatedAt), ...initiativeRecords.map((item) => item.updatedAt), ...initiativeDocuments.map((item) => item.createdAt), ...portfolio.activity.map((item) => item.createdAt)].filter((item): item is string => Boolean(item)).sort((left, right) => right.localeCompare(left))[0] || generatedAt;
  const omittedItems = Math.max(0, bundle.changeRequests.length - 4) + Math.max(0, bundle.milestones.length - 7) + Math.max(0, bundle.criteria.length - 6) + Math.max(0, (assessment?.findings.filter((item) => item.severity !== "information").length || 0) - 6);
  const wallTextLimits: Array<[string | null | undefined, number]> = [
    [initiative.title, 110], [initiative.briefingAudience, 90], [initiative.asIsStatement, 560], [initiative.toBeStatement, 560],
    [initiative.decisionAsk, 240], [initiative.desiredOutcome, 190], [initiative.consequence, 190], [initiative.successMeasures, 65],
    ...bundle.changeRequests.slice(0, 4).flatMap((request) => [[request.title, 85], [request.impactSummary || request.summary, 150]] as Array<[string | null | undefined, number]>),
    ...bundle.milestones.slice(0, 7).map((milestone) => [milestone.title, 48] as [string | null | undefined, number]),
    ...bundle.criteria.slice(0, 6).flatMap((criterion) => [[criterion.statement, 120], [criterion.evidenceReference, 70]] as Array<[string | null | undefined, number]>),
    ...keyFindings.flatMap((finding) => [[finding.title, 55], [finding.detail, 100]] as Array<[string | null | undefined, number]>),
  ];
  const truncatedWallItems = wallTextLimits.filter(([value, maximum]) => (value?.trim().length || 0) > maximum).length;
  const requiresAnnex = omittedItems > 0 || truncatedWallItems > 0;
  const unacceptableEvidence = bundle.criteria.flatMap((criterion) => ["passed", "waived"].includes(criterion.status)
    ? criterion.signoffs.filter((signoff) => ["accepted", "waived"].includes(signoff.decision) && Boolean(signoff.evidenceDocumentId) && signoff.evidenceIntegrityStatus !== "verified")
    : []);
  const printBlockReason = unacceptableEvidence.length
    ? `${unacceptableEvidence.length} completed acceptance sign-off${unacceptableEvidence.length === 1 ? " has" : "s have"} evidence that is missing, unverified, or outside the current verification envelope. Repair or re-verify it before printing.`
    : requiresAnnex && !includeAnnex
      ? "Bounded wall-sheet text continues in the traceability annex. Include the annex before printing."
      : "";
  return <main className={`initiative-one-pager ${includeAnnex ? "one-pager-with-annex" : ""}`}>
    <div className="one-pager-actions"><Link href={`/initiatives/${encodeURIComponent(initiativeId)}`}>← Return to analysis</Link>{printBlockReason ? <span className="one-pager-content-warning" role="alert">{printBlockReason}</span> : requiresAnnex ? <span className="one-pager-content-warning">{omittedItems ? `${omittedItems} additional detail items` : "Bounded wall-sheet text"} continue in the included annex.</span> : null}<label><input type="checkbox" checked={includeAnnex} onChange={(event) => setIncludeAnnex(event.target.checked)} /> Include traceability annex</label><button type="button" disabled={Boolean(printBlockReason)} title={printBlockReason || "Print the governed one-pager"} onClick={() => window.print()}>Print / Save PDF</button></div>
    <article className="wall-sheet">
      <div className="output-handling-banner">{handlingMarking}</div>
      <header className="wall-header"><div><span>JSF TECHNICAL BASELINE · DECISION SUPPORT DRAFT</span><h1>{wallText(initiative.title, 110, "Untitled Initiative")}</h1><p>{wallText(initiative.briefingAudience, 90, "Leadership audience not recorded")} · Generated {dateTimeLabel(generatedAt)} · Data through {dateTimeLabel(dataLastChangedAt)}</p></div><div className={`readiness-seal readiness-${assessment?.stage || "not_ready"}`}><strong>{assessment?.score || 0}%</strong><span>{readable(assessment?.stage || "not_ready")}</span></div></header>
      <section className="wall-state-row"><article><span>LEFT · WHERE WE ARE</span><h2>As-Is</h2><p>{wallText(initiative.asIsStatement, 560, "Current state is not yet substantiated.")}</p></article><div className="wall-change-path"><strong>{bundle.changeRequests.length}</strong><span>Change Requests</span><b>→</b><small>{bundle.objectives.length} Objectives · {effectCount} effects</small></div><article><span>RIGHT · WHERE WE NEED TO BE</span><h2>To-Be</h2><p>{wallText(initiative.toBeStatement, 560, "Target state is not yet defined.")}</p></article></section>
      <section className="wall-decision-row"><article className="wall-decision-ask"><span>THE DECISION</span><h2>{wallText(initiative.decisionAsk, 240, "Decision ask has not been recorded.")}</h2><p><strong>Needed by:</strong> {dateLabel(initiative.decisionNeededBy)} · <strong>Outcome target:</strong> {dateLabel(initiative.targetDate)}</p></article><article><span>IF FUNDED / DIRECTED</span><p>{wallText(initiative.desiredOutcome, 190, "Desired outcome not recorded.")}</p></article><article className="wall-consequence"><span>IF DEFERRED</span><p>{wallText(initiative.consequence, 190, "Consequence not recorded.")}</p></article></section>
      <section className="wall-main-grid"><article className="wall-panel wall-crs"><header><span>HOW WE GET THERE</span><strong>{assessment?.decisionsPending || 0} decisions pending</strong></header>{bundle.changeRequests.slice(0, 4).map((request, index) => { const objectiveCount = bundle.objectives.filter((item) => objectiveIsRelatedToChangeRequest(item, request.id, bundle.objectiveChangeRequestLinks)).length; return <div className="wall-cr" key={request.id}><b>{index + 1}</b><div><strong>{request.externalIdentifier} · {wallText(request.title, 85, "Untitled request")}</strong><p>{wallText(request.impactSummary || request.summary, 150, "Impact analysis missing.")}</p><small>{objectiveCount} Objectives · {request.requestedReleaseName || "No target release"}</small></div><span className={`wall-status wall-status-${request.decisionStatus}`}>{readable(request.decisionStatus)}</span></div>; })}{bundle.changeRequests.length > 4 ? <p className="wall-omission">+ {bundle.changeRequests.length - 4} additional Change Requests in the annex</p> : null}</article>
        <article className="wall-panel wall-timeline"><header><span>WHEN</span><strong>Delivery timeline</strong></header>{bundle.milestones.slice(0, 7).map((milestone) => <div className="wall-milestone" key={milestone.id}><time>{dateLabel(milestone.plannedDate)}</time><i className={`milestone-dot milestone-${milestone.status}`} /><div><strong>{wallText(milestone.title, 48, "Untitled milestone")}</strong><small>{readable(milestone.milestoneType)} · {readable(milestone.status)}</small></div></div>)}{!bundle.milestones.length && <p>No milestones recorded.</p>}</article>
        <article className="wall-panel wall-analysis"><header><span>ANALYSIS CHECK</span><strong>Claims vs assessment</strong></header><div className="wall-estimates"><div><span>Incumbent likely hours</span><strong>{compact(variance.incumbentHours)}</strong><small>{compact(variance.incumbentCost, "$")} · {Math.max(variance.incumbentHoursCoverage, variance.incumbentCostCoverage)}/{variance.objectiveCount} Objectives</small></div><div><span>Gov./independent hours</span><strong>{compact(variance.assessedHours)}</strong><small>{compact(variance.assessedCost, "$")} · {Math.max(variance.assessedHoursCoverage, variance.assessedCostCoverage)}/{variance.objectiveCount} Objectives</small></div></div><div className="wall-trace"><span>{bundle.requirements.filter((item) => ["traced", "verified", "not_applicable"].includes(item.traceStatus)).length}/{bundle.requirements.length} requirements traced</span><span>{acceptedCriteria.length}/{bundle.criteria.length} criteria accepted</span></div><p className="wall-fineprint">Totals include only Objectives with a sourced likely value and are not program-approved cost.</p></article>
      </section>
      <section className="wall-bottom-grid"><article className="wall-panel"><header><span>REQUIREMENTS & ACCEPTANCE</span><strong>{pendingCriteria.length} open criteria</strong></header><div className="wall-criteria">{bundle.criteria.slice(0, 6).map((criterion) => <div key={criterion.id}><strong>{tierLabel(criterion.tier)} · {criterion.code}</strong><p>{wallText(criterion.statement, 120, "Acceptance statement not recorded")}</p><small>{readable(criterion.status)} · {wallText(criterion.evidenceReference, 70, "Evidence pending")}</small></div>)}</div></article><article className="wall-panel wall-risks"><header><span>GAPS / KNOCK-ON EFFECTS</span><strong>{assessment?.blockers || 0} blockers · {assessment?.warnings || 0} warnings</strong></header>{keyFindings.map((finding) => <div key={finding.id}><b>{finding.severity === "blocker" ? "!" : "△"}</b><p><strong>{wallText(finding.title, 55, "Readiness finding")}</strong><span>{wallText(finding.detail, 100, "Detail not recorded")}</span></p></div>)}{!keyFindings.length && <p>No automated evidence-chain gaps detected.</p>}</article></section>
      <footer className="wall-footer"><span>{handlingMarking}</span><span>Owner: {initiative.owner || "Unassigned"}</span><span>Success: {wallText(initiative.successMeasures, 65, "Measures not recorded")}</span><span>Sources: {initiativeDocuments.length} attached documents, baseline records, Government assessments, and referenced external systems{omittedItems ? ` · ${omittedItems} detail items continue in annex` : ""}</span></footer>
    </article>
    {includeAnnex ? <article className="decision-annex">
      <div className="output-handling-banner">{handlingMarking}</div>
      <header><div><span>JSF TECHNICAL BASELINE · TRACEABILITY ANNEX</span><h1>{initiative.title}</h1><p>Supporting detail · Generated {dateTimeLabel(generatedAt)} · Data through {dateTimeLabel(dataLastChangedAt)}</p></div><div><strong>{assessment?.score || 0}%</strong><span>{readable(assessment?.stage || "not_ready")}</span></div></header>
      <section><h2>Leadership narrative</h2><h3>Decision</h3><p>{initiative.decisionAsk || "Not recorded"}</p><h3>As-Is</h3><p>{initiative.asIsStatement || "Not recorded"}</p><h3>To-Be</h3><p>{initiative.toBeStatement || "Not recorded"}</p><h3>Desired outcome</h3><p>{initiative.desiredOutcome || "Not recorded"}</p><h3>Consequence if deferred</h3><p>{initiative.consequence || "Not recorded"}</p><h3>Success measures</h3><p>{initiative.successMeasures || "Not recorded"}</p></section>
      <section><h2>External Change Request references</h2><table><thead><tr><th>Reference / analysis</th><th>External system / status</th><th>Source checked</th><th>Government decision</th></tr></thead><tbody>{bundle.changeRequests.map((request) => <tr key={request.id}><td>{request.externalIdentifier}<small>{request.title}</small><small>{request.impactSummary || request.summary || "Impact analysis not recorded"}</small></td><td>{request.externalSystem || "Not recorded"}<small>{request.externalStatus || "External status not recorded"}</small></td><td>{request.sourceAsOf || "Not recorded"}<small>{request.sourceLocator || "Locator not recorded"}</small></td><td>{readable(request.decisionStatus)}<small>{request.decisionAuthority || "Authority not recorded"}</small></td></tr>)}</tbody></table></section>
      <section><h2>Governed dependency narrative</h2><table><thead><tr><th>Dependency statement</th><th>Basis</th><th>Consequence if unmet</th><th>Confidence / source</th></tr></thead><tbody>{relevantDependencies.map((dependency) => { const predecessor = requestById.get(dependency.predecessorRequestId)?.externalIdentifier || dependency.predecessorRequestId; const successor = requestById.get(dependency.successorRequestId)?.externalIdentifier || dependency.successorRequestId; return <tr key={dependency.id}><td>{dependencyStatement(dependency, predecessor, successor)}</td><td>{dependency.rationale || "Not recorded"}</td><td>{dependency.consequenceIfUnmet || "Not assessed"}</td><td>{readable(dependency.confidence)}<small>{dependency.sourceReference || "Source not recorded"}{dependency.sourceAsOf ? ` · ${dependency.sourceAsOf}` : ""}</small></td></tr>; })}{!relevantDependencies.length ? <tr><td colSpan={4}>No Change Request dependencies are recorded for this Initiative.</td></tr> : null}</tbody></table></section>
      <section><h2>Affected technical objects</h2><table><thead><tr><th>Change Request</th><th>Action / object</th><th>State transition</th><th>Release effect</th></tr></thead><tbody>{relevantEffects.map((effect) => <tr key={effect.id}><td>{requestById.get(effect.changeRequestId)?.externalIdentifier || effect.changeRequestId}</td><td>{readable(effect.action)} {readable(effect.subjectKind)}<small>{effect.subjectLabel} · {effect.aspect}</small></td><td>{effect.currentValue || "Not reported"} → {effect.targetValue || "Not reported"}<small>{effect.consequence || "Consequence not assessed"}</small></td><td>{effect.fromReleaseName || "Current / unspecified"} → {effect.toReleaseName || "Target / unspecified"}</td></tr>)}</tbody></table></section>
      <section><h2>Objective delivery and estimates</h2><table><thead><tr><th>Objective</th><th>Schedule / status</th><th>Sourced estimates</th></tr></thead><tbody>{bundle.objectives.map((objective) => <tr key={objective.id}><td>{objective.externalIdentifier}<small>{objective.title}</small></td><td>{dateLabel(objective.plannedStart)} → {dateLabel(objective.plannedFinish)}<small>{readable(objective.status)}</small></td><td>{objective.estimates.length ? objective.estimates.map((estimate) => `${readable(estimate.estimateSource)}: ${compact(estimate.hoursLikely)}${estimate.hoursLikely === null ? "" : " h"} / ${compact(estimate.costLikely, "$")} (${estimate.asOf}; ${readable(estimate.confidence)})`).join("; ") : "No sourced estimate"}</td></tr>)}</tbody></table></section>
      <section className="annex-split"><div><h2>Requirement trace</h2>{bundle.requirements.map((requirement) => <p key={requirement.id}><strong>{requirement.externalIdentifier}</strong> · {readable(requirement.traceStatus)}<small>{requirement.title}</small><small>{requirement.rationale || "Rationale not recorded"}</small><small>{requirement.sourceLocator || "Source not recorded"}</small></p>)}</div><div><h2>Acceptance</h2>{bundle.criteria.map((criterion) => <p key={criterion.id}><strong>{tierLabel(criterion.tier)} · {criterion.code}</strong> · {readable(criterion.status)}<small>{criterion.statement}</small><small>{criterion.evidenceReference || "No text evidence reference"}</small>{criterion.signoffs.map((signoff) => <small key={signoff.id}>{signoff.signoffRole}: {readable(signoff.decision)}{signoff.signer ? ` by ${signoff.signer}` : ""}{signoff.evidenceDocumentId ? <> · <a href={`/api/documents?id=${encodeURIComponent(signoff.evidenceDocumentId)}`}>evidence ({readable(signoff.evidenceIntegrityStatus)})</a></> : ""}</small>)}</p>)}</div></section>
      <section><h2>Milestones and readiness findings</h2><table><thead><tr><th>Date / subject</th><th>Status / severity</th><th>Detail</th></tr></thead><tbody>{bundle.milestones.map((milestone) => <tr key={milestone.id}><td>{dateLabel(milestone.plannedDate)}<small>{milestone.title}</small></td><td>{readable(milestone.status)}</td><td>{milestone.consequenceIfMissed || "No downstream consequence recorded"}</td></tr>)}{assessment?.findings.map((finding) => <tr key={finding.id}><td>{finding.title}</td><td>{readable(finding.severity)}</td><td>{finding.detail}</td></tr>)}</tbody></table></section>
      <section><h2>Linked calls, decisions, and risks</h2>{initiativeRecords.length ? <table><thead><tr><th>Type</th><th>Record</th><th>Status / date</th></tr></thead><tbody>{initiativeRecords.map((record) => <tr key={record.id}><td>{readable(record.recordType)}</td><td>{record.title}<small>{record.summary || "No summary recorded"}</small></td><td>{readable(record.status)}<small>{record.occurredAt ? dateLabel(record.occurredAt) : "Date not recorded"}</small></td></tr>)}</tbody></table> : <p>No linked calls, decisions, risks, questions, or technical notes are recorded.</p>}</section>
      <section><h2>Supporting documents</h2>{initiativeDocuments.length ? <table><thead><tr><th>Document</th><th>What it substantiates</th><th>Attached</th><th>Reference</th></tr></thead><tbody>{initiativeDocuments.map((document) => <tr key={document.id}><td><a href={`/api/documents?id=${encodeURIComponent(document.id)}`}>{document.fileName}</a></td><td>{document.description || "Not described"}</td><td>{dateTimeLabel(document.createdAt)}</td><td>{document.id}</td></tr>)}</tbody></table> : <p>No supporting documents are attached to this Initiative.</p>}</section>
      <footer>{handlingMarking} · Generated from the governed application dataset. External Change Requests remain controlled in their originating system.</footer>
    </article> : null}
  </main>;
}
