"use client";
import Link from "../../components/app-link";
import { DomainPageShell } from "../../components/domain-shell";
import { useControlSnapshot } from "../../lib/control-client";
export default function ControlPage() {
  const { snapshot, loading, error } = useControlSnapshot();
  if (loading) return <DomainPageShell title="Analyst Control" subtitle="Loading control checks…" contextMode="portfolio"><p>Loading control checks…</p></DomainPageShell>;
  if (error || !snapshot) return <DomainPageShell title="Analyst Control" subtitle="Control checks are unavailable." contextMode="portfolio"><p className="error-copy">{error}</p></DomainPageShell>;
  const blockers = snapshot.queues.filter((item) => item.severity === "blocker").length;
  const warnings = snapshot.queues.filter((item) => item.severity === "warning").length;
  return <DomainPageShell title="Analyst Control" subtitle="Action queues for baseline stewardship, fielding context, delivery evidence, and funding decisions." releaseScope={`${blockers} blockers · ${warnings} warnings`} contextMode="portfolio" actions={<Link className="primary-button" href="/reports">Leadership reports</Link>}>
    <section className="decision-principle"><strong>Control rule</strong><span>This page identifies records that require analyst action. It is not an executive dashboard. Every count links to the object that must be corrected or completed.</span></section>
    <section className="summary"><div className="metric"><span>Active baseline</span><strong>{snapshot.counts.activeRecords}</strong><small>{snapshot.counts.unreviewedRecords} require review · {snapshot.counts.voidedRecords} voided</small></div><div className={`metric ${snapshot.counts.unmappedPlatforms ? "metric-alert" : ""}`}><span>Platform coverage</span><strong>{snapshot.counts.activeRecords - snapshot.counts.unmappedPlatforms}/{snapshot.counts.activeRecords}</strong><small>Primary fielding assignments</small></div><div className={`metric ${snapshot.counts.pendingDecisions ? "metric-alert" : ""}`}><span>Funding decisions</span><strong>{snapshot.counts.pendingDecisions}</strong><small>Change Requests pending</small></div><div className={`metric ${snapshot.counts.objectiveGaps + snapshot.counts.initiativeGaps ? "metric-alert" : ""}`}><span>Briefing gaps</span><strong>{snapshot.counts.objectiveGaps + snapshot.counts.initiativeGaps}</strong><small>Objectives and Initiatives incomplete</small></div></section>
    <section className="domain-section"><div className="section-toolbar"><div><span className="eyebrow">CURRENT A2O EXCHANGE PACKAGE</span><h3>{snapshot.source.fileName || "No exchange file loaded"}</h3></div><Link href="/intake">A2O exchange and quality</Link></div><div className="record-facts"><div><dt>Received</dt><dd>{snapshot.source.receivedAt ? new Date(snapshot.source.receivedAt).toLocaleString() : "Not available"}</dd></div><div><dt>Status</dt><dd>{snapshot.source.status || "Not loaded"}</dd></div><div><dt>Rows</dt><dd>{snapshot.source.rowCount}</dd></div><div><dt>Accepted / exceptions</dt><dd>{snapshot.source.acceptedCount} / {snapshot.source.exceptionCount}</dd></div></div></section>
    <section className="domain-section"><div className="section-toolbar"><div><span className="eyebrow">ACTION QUEUE</span><h3>Records requiring analyst disposition</h3></div><span>Generated {new Date(snapshot.generatedAt).toLocaleString()}</span></div><div className="control-queue">{snapshot.queues.map((item) => <Link className={`control-item control-${item.severity}`} href={item.href} key={item.id}><span>{item.category}</span><strong>{item.title}</strong><p>{item.detail}</p><b>Open record →</b></Link>)}</div></section>
    <section className="domain-section"><div className="section-toolbar"><div><span className="eyebrow">STEWARDSHIP COVERAGE</span><h3>Governed extensions</h3></div></div><div className="chip-list"><Link className="domain-chip" href="/stewardship"><strong>{snapshot.counts.acceptedAliases} canonical aliases</strong><span>Identity decisions</span></Link><Link className="domain-chip" href="/platforms"><strong>{snapshot.counts.unmappedPlatforms} unmapped records</strong><span>Platform assignments</span></Link><Link className="domain-chip" href="/delivery"><strong>{snapshot.counts.deliveryRisks} schedule risks</strong><span>Milestones and WBS</span></Link><Link className="domain-chip" href="/evidence"><strong>{snapshot.counts.callActions} call follow-ups</strong><span>Open actions and clarifications</span></Link></div></section>
  </DomainPageShell>;
}
